language: php

php:
  - 5.6
  - 5.5
  - 5.4

mysql:
  database: BoltPHP
  username: BoltPHP
  encoding: utf8

before_install:
  - sudo apt-get update > /dev/null

before_script:
  - phpenv config-add Bolt/Tests/test.php.ini
  - mysql -e 'create database IF NOT EXISTS BoltPHP;'

script: phpunit --configuration phpunit.xml

notifications:
  email:
    - cdtreeks@gmail.com
  on_success: change
  on_failure: change