language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

script: phpunit --configuration phpunit.xml

mysql:
  database: travis_ci_test
  username: travis_ci_test
  encoding: utf8

before_install:
  - sudo apt-get update > /dev/null

before_script: phpenv config-add Bolt/Tests/test.php.ini